name: Helm Chart Test
description: 'Lint and test helm charts'
inputs:
  chart:
    description: 'Path to the chart to be tested'
    required: true
  deploy_token:
    description: 'Token to access the Helm repo'
    required: true
  release:
    description: 'Should the chart be released'
    default: 'false'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: "Build chart"
      shell: bash
      run: |
         set -x
         if [ ! -d "./.ct" ]; then
           cp -R $GITHUB_ACTION_PATH/.ct .
         fi
         $GITHUB_ACTION_PATH/build.sh ${{ inputs.chart }}
    - name: "Release chart"
      if: ${{ inputs.release }} == 'true'
      shell: bash
      run: |
           apk add --update git openssh-client sed rsync
           mkdir -p ~/.ssh/
           echo "{{ $inputs.deploy_token }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           git config --global user.email "foerster@forestsoft.de"
           git config --global user.name "Sebastian"
           $GITHUB_ACTION_PATH/release.sh
