name: Helm Chart Test
description: 'Lint and test helm charts'
inputs:
  chart:
    description: 'Path to the chart to be tested'
    required: true
  deploy_token:
    description: 'Token to access the Helm repo'
    required: true
  kubeconfig:
    description: 'key for kubernetes config'
    required: true
  release:
    description: 'Should the chart be released'
    default: 'false'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: "Setup"
      shell: bash
      run: |
         git config --global --add safe.directory $(pwd)
         mkdir -p /root/.kube/
         echo "${{ inputs.kubeconfig }}" | base64 -d  >  /root/.kube/config
         mkdir -p ~/.kube/
         echo "${{ inputs.kubeconfig }}" | base64 -d  >  ~/.kube/config
         export CI_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
         echo "${{ inputs.deploy_token }}" > /root/.ssh/id_rsa
         chmod 600 /root/.ssh/id_rsa
         chmod 600 /root/.kube/config
         chmod 600 ~/.kube/config
    - name: "Build chart"
      shell: bash
      run: |
         set -x
         /ct/build.sh ${{ inputs.chart }}
    - name: "Release chart"
      if: inputs.release == 'true'
      shell: bash
      run: |
           /ct/release.sh
