name: Helm Chart Test
description: 'Lint and test helm charts'
inputs:
  chart:
    description: 'Path to the chart to be tested'
    required: true
  deploy_token:
    description: 'Token to access the Helm repo'
    required: true
  release:
    description: 'Should the chart be released'
    default: 'false'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: "Build chart"
      shell: bash
      run: |
         set -x
         pwd
         ls -la .
         /ct/build.sh ${{ inputs.chart }}
    - name: "Release chart"
      if: inputs.release == 'true'
      shell: bash
      run: |
           export CI_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
           echo "${{ inputs.deploy_token }}" > /root/.ssh/id_rsa
           chmod 600 /root/.ssh/id_rsa
           /ct/release.sh
